"""
Auto-generated skeleton tests from Markdown specs.
Regenerate using: specleft test skeleton

Generated by SpecLeft - https://github.com/SpecLeft/specleft
"""

import pytest
from fastapi.testclient import TestClient
from main import app
from specleft import specleft

client = TestClient(app)

# =============================================================================
# Feature: Auth Service
# ID: auth
# =============================================================================

# Story: Default
# ID: default


@specleft(
    feature_id="auth",
    scenario_id="successful-registration",
    skip=False,
    reason="Skeleton test - not yet implemented",
)
def test_successful_registration():
    """Successful Registration

    Priority: high
    """
    user_data = {"username": "alice", "password": "secret"}
    response = None

    with specleft.step('Given a new user "alice" with password "secret"'):
        # In-memory reset happens on app restart, nothing to do
        pass

    with specleft.step("When they register"):
        response = client.post("/register", json=user_data)

    with specleft.step("Then the user is created successfully"):
        assert response.status_code == 201
        assert response.json()["msg"] == "User created"

    with specleft.step("And the response status is 201"):
        assert response.status_code == 201


@specleft(
    feature_id="auth",
    scenario_id="duplicate-username",
    skip=False,
    reason="Skeleton test - not yet implemented",
)
def test_duplicate_username():
    """Duplicate Username

    Priority: medium
    """
    user_data = {"username": "alice", "password": "secret"}
    response = None

    with specleft.step('Given an existing user "alice"'):
        client.post("/register", json=user_data)

    with specleft.step('When a new user tries to register as "alice"'):
        response = client.post("/register", json=user_data)

    with specleft.step("Then the registration fails"):
        assert response.status_code == 400

    with specleft.step("And the response status is 400"):
        assert response.status_code == 400


@specleft(
    feature_id="auth",
    scenario_id="successful-login",
    skip=False,
    reason="Skeleton test - not yet implemented",
)
def test_successful_login():
    """Successful Login

    Priority: high
    """
    user_data = {"username": "alice", "password": "secret"}
    # Ensure user exists
    client.post("/register", json=user_data)
    response = None

    with specleft.step('Given a user "alice" with password "secret"'):
        # Setup done above
        pass

    with specleft.step('When they log in with "alice" and "secret"'):
        response = client.post(
            "/token", data={"username": "alice", "password": "secret"}
        )

    with specleft.step("Then a valid access token is returned"):
        assert response.status_code == 200
        data = response.json()
        assert "access_token" in data
        assert data["token_type"] == "bearer"

    with specleft.step("And the response status is 200"):
        assert response.status_code == 200


@specleft(
    feature_id="auth",
    scenario_id="invalid-password",
    skip=False,
    reason="Skeleton test - not yet implemented",
)
def test_invalid_password():
    """Invalid Password

    Priority: medium
    """
    user_data = {"username": "alice", "password": "secret"}
    client.post("/register", json=user_data)
    response = None

    with specleft.step('Given a user "alice" with password "secret"'):
        pass

    with specleft.step('When they log in with "alice" and "wrongpass"'):
        response = client.post(
            "/token", data={"username": "alice", "password": "wrongpass"}
        )

    with specleft.step("Then the login fails"):
        assert response.status_code == 401

    with specleft.step("And the response status is 401"):
        assert response.status_code == 401


@specleft(
    feature_id="auth",
    scenario_id="access-protected-route",
    skip=False,
    reason="Skeleton test - not yet implemented",
)
def test_access_protected_route():
    """Access Protected Route

    Priority: high
    """
    user_data = {"username": "alice", "password": "secret"}
    client.post("/register", json=user_data)
    token_response = client.post(
        "/token", data={"username": "alice", "password": "secret"}
    )
    token = token_response.json()["access_token"]
    response = None

    with specleft.step('Given a valid access token for "alice"'):
        pass

    with specleft.step("When they access the protected endpoint"):
        response = client.get("/users/me", headers={"Authorization": f"Bearer {token}"})

    with specleft.step("Then the request is successful"):
        assert response.status_code == 200

    with specleft.step('And the response contains the username "alice"'):
        assert response.json()["username"] == "alice"


@specleft(
    feature_id="auth",
    scenario_id="access-without-token",
    skip=False,
    reason="Skeleton test - not yet implemented",
)
def test_access_without_token():
    """Access Without Token

    Priority: high
    """
    response = None

    with specleft.step("Given no access token"):
        pass

    with specleft.step("When they access the protected endpoint"):
        response = client.get("/users/me")

    with specleft.step("Then the request is denied"):
        assert response.status_code == 401

    with specleft.step("And the response status is 401"):
        assert response.status_code == 401
